name: CI

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract Node.js version
        id: node_version
        run: echo "NODE_VERSION=$(jq -r .engines.node package.json)" >> $GITHUB_ENV
        shell: bash

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Set Nx SHAs
        uses: nrwl/nx-set-shas@v4

      - name: Install
        run: |
          corepack enable
          pnpm install --frozen-lockfile --ignore-scripts
        shell: bash

      - name: Set environment variables
        run: |
          echo "BASE=${{ inputs.base }}" >> $GITHUB_ENV
          echo "HEAD=${{ inputs.head }}" >> $GITHUB_ENV
          echo "BASE_PATH=${{ inputs.base_path }}" >> $GITHUB_ENV
        shell: bash

      - name: Check formatting
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t format:check --parallel=3 --verbose
        shell: bash

      - name: Build
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t build --exclude='tag:type:app' --parallel=3 --verbose
        shell: bash

      - name: Lint
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t lint --parallel=3 --verbose
        shell: bash

      - name: Build apps
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t build --exclude='*,!tag:type:app' --parallel=3 --verbose
        shell: bash

      - name: Check types
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t types:check --parallel=3 --verbose
        shell: bash

      - name: Test
        run: |
          pnpm nx affected --base=$BASE --head=$HEAD -t test --parallel=3 --verbose
        shell: bash
